version: '3.3'

# para correr solo la base de datos:
# docker-compose run --service-ports database

services:
  database:
    image: mysql:8.0.12
    #    command: --default-authentication-plugin=mysql_native_password
    #container_name: birra_container
    environment:
      MYSQL_DATABASE: birradb
      MYSQL_USER: birrauser
      MYSQL_PASSWORD: birra1337
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  back:
    image: nicolasmoreno/birraapp-backend
    #container_name: birra_container
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/birradb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: birrauser
      SPRING_DATASOURCE_PASSWORD: birra1337
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "80:8080"
    depends_on:
      - database
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
